# -*- coding: utf-8 -*-
"""HW2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u3LSF3C9Vz4klvbpGhM5Q2r6ArHkv7Dr
"""

install.packages("tidyverse")
install.packages("openintro")
library(tidyverse)
library(openintro)

View(seattlepets)

nrow(seattlepets)

seattlepets %>%
  count(animal_name, sort = TRUE)

seattlepets %>%
  group_by(species) %>%
  count(animal_name, sort = TRUE)

seattlepets %>%
  group_by(species) %>%
  count(animal_name, sort = TRUE) %>%
  slice_max(n, n = 5)

seattlepets %>%
  group_by(species) %>%
  count(animal_name, sort = TRUE) %>%
  slice_max(n, n = 5) %>%
  arrange(species, n)

seattlepets %>%
  group_by(species) %>%
  count(animal_name, sort = TRUE) %>%
  slice_max(n, n = 5) %>%
  arrange(n, species)